apiVersion: v2
name: glua-webhook
description: A Kubernetes mutating webhook powered by Lua scripts
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - webhook
  - mutating
  - lua
  - kubernetes
maintainers:
  - name: Thomas Maurice
