apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glua-webhook.fullname" . }}
  labels:
    {{- include "glua-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "glua-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/script: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "glua-webhook.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glua-webhook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: webhook
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --address=:8443
        - --cert=/etc/webhook/certs/tls.crt
        - --key=/etc/webhook/certs/tls.key
        - --script=/etc/webhook/scripts/mutate.lua
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: certs
          mountPath: /etc/webhook/certs
          readOnly: true
        - name: scripts
          mountPath: /etc/webhook/scripts
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: {{ include "glua-webhook.fullname" . }}-tls
      - name: scripts
        configMap:
          name: {{ include "glua-webhook.fullname" . }}-scripts
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
